name: release-logs
version: 0.2.0
usage: Get debug info about resources created by a release.
description: A Helm plugin to get debug information about the Kubernetes resources creaeted by a release.
command: $HELM_PLUGIN_DIR/release-logs.sh
